=== learn-medi-ch/medi-course-management-backend/app/schemas/medi-course-management-backend-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://fluxlabs.ch/medi-course-management-backend",
  "allOf": [
    {
      "$ref": "../../../flux-eco/schemas/flux-eco-app-config-schema.json"
    }
  ],
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "const": "medi-course-management-backend"
    },
    "inboundsConfig": {
      "httpBindingConfig": {
        "$ref": "../../../flux-eco/schemas/binding-schemas/http-schemas/flux-eco-http-binding-config-schema.json"
      }
    },
    "apiConfig": {
      "$ref": "medi-course-management-backend-api-schema.json"
    },
    "outboundsConfigs": {
      "type": "object",
      "properties": {
        "iliasDatabase": {
          "type": "object",
          "properties": {
            "server": {
              "$ref": "../../../flux-eco-query-actions/app/schemas/flux-eco-query-actions-schema.json#/$defs/server"
            },
            "boundActions": {
              "type": "object",
              "properties": {
                "getRepositoryTree": {
                  "$ref": "../../../flux-eco-query-actions/app/schemas/flux-eco-query-actions-schema.json#/$defs/actions/queryMysqlDataSource"
                }
              },
              "required": [
                "getRepositoryTree"
              ]
            }
          }
        }
      },
      "required": ["iliasDatabase"]
    }
  }
}

=== learn-medi-ch/medi-course-management-backend/app/config/config.json
{
  "$schema": "../schemas/medi-course-management-backend-schema.json",
  "name": "medi-course-management-backend",
  "inboundsConfig": {
    "httpBindingConfig": {
      "server": {
        "port": "${SERVER_PORT}",
        "host": "${SERVER_HOST}"
      },
      "policies": {
        "authenticatedUsersOnly": {
          "path": "/api",
          "allowedHeaders": "${SERVER_REQUIRED_HEADERS}",
          "allowedIps": "${SERVER_ALLOWED_IPS}"
        }
      },
      "routes": {
        "api": {
          "/api/{pageName}/readPageStructure": {
            "contentType": "application/json",
            "parameterNames": [
              "pageName"
            ],
            "actionName": "readPageStructure",
            "actionType": "requestHandler"
          }
        }
      },
      "staticFilesPath": null
    }
  },
  "apiConfig": {
    "outbounds": {
      "queryHandler": {
        "actionName": "handle",
        "parametersMapping": {
        }
      }
    }
  },
  "outboundsConfigs": {
    "iliasDatabase": {
      "server": {
        "port": "${DATABASE_PORT}",
        "host": "${DATABASE_HOST}",
        "database": "${DATABASE_DATABASE}",
        "password": "${DATABASE_PASSWORD}",
        "user": "${DATABASE_USER}"
      },
      "boundActions": {
        "getRepositoryTree": {
          "actionName": "queryMysqlDataSource",
          "actionParameters": {
            "tableName": "object_data",
            "joins": [
              {
                "tableName": "object_reference",
                "type": "INNER JOIN",
                "condition": {
                  "leftTableField": "object_data.obj_id",
                  "operator": "=",
                  "rightTableField": "object_reference.obj_id"
                }
              },
              {
                "tableName": "tree",
                "type": "INNER JOIN",
                "condition": {
                  "leftTableField": "object_reference.ref_id",
                  "operator": "=",
                  "rightTableField": "tree.child"
                }
              }
            ],
            "queryOptions": {
              "responseTemplate": {
                "parentId": "parent_id",
                "nodeId": "ref_id",
                "nodeData": {
                  "label": "title"
                }
              }
            }
          }
        }
      }
    }
  }
}
